#!/bin/sh
set -eu
SCRIPT_DIR="$(realpath -- "$(dirname -- "$0")")"; readonly SCRIPT_DIR;
print() { printf "%b%b" "${1-""}" "${2-"\\n"}"; }
stderr() { print "$@" 1>&2; }
reportError() { stderr "$2"; return "$1"; }
verbosePrint() { { test -n "${VERBOSE_MODE+x}" && stderr "$@"; } || true; }

commandv() { command -v "$1" || reportError "$?" "Executable '$1' not found"; }



SOURCE_URL="${SOURCE_URL:?"Missing SOURCE_URL"}"
OUTPUT_DIR="${OUTPUT_DIR:?"Missing OUTPUT_DIR"}"

STATUS_FILE="$OUTPUT_DIR/completed.status"



hashFiles() {
	(cd "$OUTPUT_DIR" && find . -type f \! -name completed.status -exec sha256sum {} \+ ;) | sort -k 2
}

checkIntegrity() {
	_STATUS_FILE="$1"
	awk 'NF > 0 && !/^[[:space:]]*#/' "$_STATUS_FILE" | { cd "$OUTPUT_DIR" && sha256sum -c --strict; }
}



if test -f "$STATUS_FILE"; then
	stderr "Found downloaded files.\nDoing integrity test..."

	checkIntegrity "$STATUS_FILE"

	stderr "Passed integrity check."
	exit
fi




cleanupTmpDir() { rm -rf "$TMP_DIR"; }
TMP_DIR="$(mktemp -d -p "/tmp")"; readonly TMP_DIR
trap 'cleanupTmpDir; trap - EXIT' EXIT INT HUP TERM # Safely remove tmp dir on exit or interrupt


ZIP_FILE="yelp.zip"


stderr "Downloading file from source..."
curl -sSfL -o "$ZIP_FILE" "$SOURCE_URL"

stderr "Unzipping file..."
unzip -j "$ZIP_FILE" "Yelp JSON/yelp_dataset.tar" -d "$TMP_DIR"

TAR_FILE="$TMP_DIR/yelp_dataset.tar"


stderr "Untaring files..."
tar -xvf "$TAR_FILE"  -C "$OUTPUT_DIR" \
	yelp_academic_dataset_business.json \
	yelp_academic_dataset_checkin.json \
	yelp_academic_dataset_review.json \
	yelp_academic_dataset_tip.json \
	yelp_academic_dataset_user.json

stderr "Generating status file."

tee "$STATUS_FILE" <<EOF
# Completed download of dataset
# Original source URL: $SOURCE_URL
# SHA256 sum of the output files:
$(hashFiles)
EOF

stderr "File download and extration completed."
