apiVersion: v1
kind: Pod
metadata:
  name: debian-data-reader
spec:
  containers:
    - name: debian-data-reader
      image: debian
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash"]
      args: ["-c", "while true; do ls -l /data; sleep 30; done"]
      volumeMounts:
        - name: data
          mountPath: /data
      workingDir: /data
      resources:
        requests:
          cpu: "2"
          memory: "8Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: weather-data-pvc
  restartPolicy: Never
