apiVersion: v1
kind: Pod
metadata:
  name: go-producer
spec:
  containers:
    - name: go-producer
      image: golang:1.25.3-trixie
      command: [ "sleep", "infinity" ] # Keeps it running. Inspired by E24L3
      volumeMounts:
        - name: data
          mountPath: /data
      workingDir: /data
      resources:
        requests:
          cpu: "2"
          memory: "8Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: weather-data-pvc
  restartPolicy: Never
