apiVersion: v1
kind: Pod
metadata:
  name: weather-producer
spec:
  containers:
    - name: weather-producer
      image: the1s/big-data-producer:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: data
          mountPath: /data
      workingDir: /data
      resources:
        requests:
          cpu: "2"
          memory: "512Mi"
        limits:
          cpu: "4"
          memory: "8Gi"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: weather-data-pvc
  restartPolicy: Never
