/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dk.sdu.bigdata.weather.producer.core;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WeatherEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6948264584523279278L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherEvent\",\"namespace\":\"dk.sdu.bigdata.weather.producer.core\",\"fields\":[{\"name\":\"Station\",\"type\":\"long\"},{\"name\":\"Date\",\"type\":\"string\"},{\"name\":\"Latitude\",\"type\":\"double\"},{\"name\":\"Longitude\",\"type\":\"double\"},{\"name\":\"Elevation\",\"type\":\"double\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"ReportType\",\"type\":\"string\"},{\"name\":\"Source\",\"type\":[\"null\",\"string\",\"int\"],\"default\":null},{\"name\":\"HourlyDryBulbTemperature\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"HourlySeaLevelPressure\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"HourlyVisibility\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"HourlyWindDirection\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"HourlyWindSpeed\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"HourlyPrecipitation\",\"type\":[\"null\",\"string\",\"double\"],\"default\":null},{\"name\":\"HourlyRelativeHumidity\",\"type\":[\"null\",\"double\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WeatherEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WeatherEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WeatherEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WeatherEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WeatherEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WeatherEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WeatherEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WeatherEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WeatherEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long Station;
  private java.lang.CharSequence Date;
  private double Latitude;
  private double Longitude;
  private double Elevation;
  private java.lang.CharSequence Name;
  private java.lang.CharSequence ReportType;
  private java.lang.Object Source;
  private java.lang.Double HourlyDryBulbTemperature;
  private java.lang.Double HourlySeaLevelPressure;
  private java.lang.Double HourlyVisibility;
  private java.lang.Double HourlyWindDirection;
  private java.lang.Double HourlyWindSpeed;
  private java.lang.Object HourlyPrecipitation;
  private java.lang.Double HourlyRelativeHumidity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeatherEvent() {}

  /**
   * All-args constructor.
   * @param Station The new value for Station
   * @param Date The new value for Date
   * @param Latitude The new value for Latitude
   * @param Longitude The new value for Longitude
   * @param Elevation The new value for Elevation
   * @param Name The new value for Name
   * @param ReportType The new value for ReportType
   * @param Source The new value for Source
   * @param HourlyDryBulbTemperature The new value for HourlyDryBulbTemperature
   * @param HourlySeaLevelPressure The new value for HourlySeaLevelPressure
   * @param HourlyVisibility The new value for HourlyVisibility
   * @param HourlyWindDirection The new value for HourlyWindDirection
   * @param HourlyWindSpeed The new value for HourlyWindSpeed
   * @param HourlyPrecipitation The new value for HourlyPrecipitation
   * @param HourlyRelativeHumidity The new value for HourlyRelativeHumidity
   */
  public WeatherEvent(java.lang.Long Station, java.lang.CharSequence Date, java.lang.Double Latitude, java.lang.Double Longitude, java.lang.Double Elevation, java.lang.CharSequence Name, java.lang.CharSequence ReportType, java.lang.Object Source, java.lang.Double HourlyDryBulbTemperature, java.lang.Double HourlySeaLevelPressure, java.lang.Double HourlyVisibility, java.lang.Double HourlyWindDirection, java.lang.Double HourlyWindSpeed, java.lang.Object HourlyPrecipitation, java.lang.Double HourlyRelativeHumidity) {
    this.Station = Station;
    this.Date = Date;
    this.Latitude = Latitude;
    this.Longitude = Longitude;
    this.Elevation = Elevation;
    this.Name = Name;
    this.ReportType = ReportType;
    this.Source = Source;
    this.HourlyDryBulbTemperature = HourlyDryBulbTemperature;
    this.HourlySeaLevelPressure = HourlySeaLevelPressure;
    this.HourlyVisibility = HourlyVisibility;
    this.HourlyWindDirection = HourlyWindDirection;
    this.HourlyWindSpeed = HourlyWindSpeed;
    this.HourlyPrecipitation = HourlyPrecipitation;
    this.HourlyRelativeHumidity = HourlyRelativeHumidity;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Station;
    case 1: return Date;
    case 2: return Latitude;
    case 3: return Longitude;
    case 4: return Elevation;
    case 5: return Name;
    case 6: return ReportType;
    case 7: return Source;
    case 8: return HourlyDryBulbTemperature;
    case 9: return HourlySeaLevelPressure;
    case 10: return HourlyVisibility;
    case 11: return HourlyWindDirection;
    case 12: return HourlyWindSpeed;
    case 13: return HourlyPrecipitation;
    case 14: return HourlyRelativeHumidity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Station = (java.lang.Long)value$; break;
    case 1: Date = (java.lang.CharSequence)value$; break;
    case 2: Latitude = (java.lang.Double)value$; break;
    case 3: Longitude = (java.lang.Double)value$; break;
    case 4: Elevation = (java.lang.Double)value$; break;
    case 5: Name = (java.lang.CharSequence)value$; break;
    case 6: ReportType = (java.lang.CharSequence)value$; break;
    case 7: Source = value$; break;
    case 8: HourlyDryBulbTemperature = (java.lang.Double)value$; break;
    case 9: HourlySeaLevelPressure = (java.lang.Double)value$; break;
    case 10: HourlyVisibility = (java.lang.Double)value$; break;
    case 11: HourlyWindDirection = (java.lang.Double)value$; break;
    case 12: HourlyWindSpeed = (java.lang.Double)value$; break;
    case 13: HourlyPrecipitation = value$; break;
    case 14: HourlyRelativeHumidity = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Station' field.
   * @return The value of the 'Station' field.
   */
  public long getStation() {
    return Station;
  }


  /**
   * Sets the value of the 'Station' field.
   * @param value the value to set.
   */
  public void setStation(long value) {
    this.Station = value;
  }

  /**
   * Gets the value of the 'Date' field.
   * @return The value of the 'Date' field.
   */
  public java.lang.CharSequence getDate() {
    return Date;
  }


  /**
   * Sets the value of the 'Date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.Date = value;
  }

  /**
   * Gets the value of the 'Latitude' field.
   * @return The value of the 'Latitude' field.
   */
  public double getLatitude() {
    return Latitude;
  }


  /**
   * Sets the value of the 'Latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.Latitude = value;
  }

  /**
   * Gets the value of the 'Longitude' field.
   * @return The value of the 'Longitude' field.
   */
  public double getLongitude() {
    return Longitude;
  }


  /**
   * Sets the value of the 'Longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.Longitude = value;
  }

  /**
   * Gets the value of the 'Elevation' field.
   * @return The value of the 'Elevation' field.
   */
  public double getElevation() {
    return Elevation;
  }


  /**
   * Sets the value of the 'Elevation' field.
   * @param value the value to set.
   */
  public void setElevation(double value) {
    this.Elevation = value;
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }


  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'ReportType' field.
   * @return The value of the 'ReportType' field.
   */
  public java.lang.CharSequence getReportType() {
    return ReportType;
  }


  /**
   * Sets the value of the 'ReportType' field.
   * @param value the value to set.
   */
  public void setReportType(java.lang.CharSequence value) {
    this.ReportType = value;
  }

  /**
   * Gets the value of the 'Source' field.
   * @return The value of the 'Source' field.
   */
  public java.lang.Object getSource() {
    return Source;
  }


  /**
   * Sets the value of the 'Source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.Object value) {
    this.Source = value;
  }

  /**
   * Gets the value of the 'HourlyDryBulbTemperature' field.
   * @return The value of the 'HourlyDryBulbTemperature' field.
   */
  public java.lang.Double getHourlyDryBulbTemperature() {
    return HourlyDryBulbTemperature;
  }


  /**
   * Sets the value of the 'HourlyDryBulbTemperature' field.
   * @param value the value to set.
   */
  public void setHourlyDryBulbTemperature(java.lang.Double value) {
    this.HourlyDryBulbTemperature = value;
  }

  /**
   * Gets the value of the 'HourlySeaLevelPressure' field.
   * @return The value of the 'HourlySeaLevelPressure' field.
   */
  public java.lang.Double getHourlySeaLevelPressure() {
    return HourlySeaLevelPressure;
  }


  /**
   * Sets the value of the 'HourlySeaLevelPressure' field.
   * @param value the value to set.
   */
  public void setHourlySeaLevelPressure(java.lang.Double value) {
    this.HourlySeaLevelPressure = value;
  }

  /**
   * Gets the value of the 'HourlyVisibility' field.
   * @return The value of the 'HourlyVisibility' field.
   */
  public java.lang.Double getHourlyVisibility() {
    return HourlyVisibility;
  }


  /**
   * Sets the value of the 'HourlyVisibility' field.
   * @param value the value to set.
   */
  public void setHourlyVisibility(java.lang.Double value) {
    this.HourlyVisibility = value;
  }

  /**
   * Gets the value of the 'HourlyWindDirection' field.
   * @return The value of the 'HourlyWindDirection' field.
   */
  public java.lang.Double getHourlyWindDirection() {
    return HourlyWindDirection;
  }


  /**
   * Sets the value of the 'HourlyWindDirection' field.
   * @param value the value to set.
   */
  public void setHourlyWindDirection(java.lang.Double value) {
    this.HourlyWindDirection = value;
  }

  /**
   * Gets the value of the 'HourlyWindSpeed' field.
   * @return The value of the 'HourlyWindSpeed' field.
   */
  public java.lang.Double getHourlyWindSpeed() {
    return HourlyWindSpeed;
  }


  /**
   * Sets the value of the 'HourlyWindSpeed' field.
   * @param value the value to set.
   */
  public void setHourlyWindSpeed(java.lang.Double value) {
    this.HourlyWindSpeed = value;
  }

  /**
   * Gets the value of the 'HourlyPrecipitation' field.
   * @return The value of the 'HourlyPrecipitation' field.
   */
  public java.lang.Object getHourlyPrecipitation() {
    return HourlyPrecipitation;
  }


  /**
   * Sets the value of the 'HourlyPrecipitation' field.
   * @param value the value to set.
   */
  public void setHourlyPrecipitation(java.lang.Object value) {
    this.HourlyPrecipitation = value;
  }

  /**
   * Gets the value of the 'HourlyRelativeHumidity' field.
   * @return The value of the 'HourlyRelativeHumidity' field.
   */
  public java.lang.Double getHourlyRelativeHumidity() {
    return HourlyRelativeHumidity;
  }


  /**
   * Sets the value of the 'HourlyRelativeHumidity' field.
   * @param value the value to set.
   */
  public void setHourlyRelativeHumidity(java.lang.Double value) {
    this.HourlyRelativeHumidity = value;
  }

  /**
   * Creates a new WeatherEvent RecordBuilder.
   * @return A new WeatherEvent RecordBuilder
   */
  public static dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder newBuilder() {
    return new dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder();
  }

  /**
   * Creates a new WeatherEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WeatherEvent RecordBuilder
   */
  public static dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder newBuilder(dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder other) {
    if (other == null) {
      return new dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder();
    } else {
      return new dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder(other);
    }
  }

  /**
   * Creates a new WeatherEvent RecordBuilder by copying an existing WeatherEvent instance.
   * @param other The existing instance to copy.
   * @return A new WeatherEvent RecordBuilder
   */
  public static dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder newBuilder(dk.sdu.bigdata.weather.producer.core.WeatherEvent other) {
    if (other == null) {
      return new dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder();
    } else {
      return new dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for WeatherEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherEvent>
    implements org.apache.avro.data.RecordBuilder<WeatherEvent> {

    private long Station;
    private java.lang.CharSequence Date;
    private double Latitude;
    private double Longitude;
    private double Elevation;
    private java.lang.CharSequence Name;
    private java.lang.CharSequence ReportType;
    private java.lang.Object Source;
    private java.lang.Double HourlyDryBulbTemperature;
    private java.lang.Double HourlySeaLevelPressure;
    private java.lang.Double HourlyVisibility;
    private java.lang.Double HourlyWindDirection;
    private java.lang.Double HourlyWindSpeed;
    private java.lang.Object HourlyPrecipitation;
    private java.lang.Double HourlyRelativeHumidity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Station)) {
        this.Station = data().deepCopy(fields()[0].schema(), other.Station);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Date)) {
        this.Date = data().deepCopy(fields()[1].schema(), other.Date);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Latitude)) {
        this.Latitude = data().deepCopy(fields()[2].schema(), other.Latitude);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.Longitude)) {
        this.Longitude = data().deepCopy(fields()[3].schema(), other.Longitude);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.Elevation)) {
        this.Elevation = data().deepCopy(fields()[4].schema(), other.Elevation);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.Name)) {
        this.Name = data().deepCopy(fields()[5].schema(), other.Name);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.ReportType)) {
        this.ReportType = data().deepCopy(fields()[6].schema(), other.ReportType);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.Source)) {
        this.Source = data().deepCopy(fields()[7].schema(), other.Source);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.HourlyDryBulbTemperature)) {
        this.HourlyDryBulbTemperature = data().deepCopy(fields()[8].schema(), other.HourlyDryBulbTemperature);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.HourlySeaLevelPressure)) {
        this.HourlySeaLevelPressure = data().deepCopy(fields()[9].schema(), other.HourlySeaLevelPressure);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.HourlyVisibility)) {
        this.HourlyVisibility = data().deepCopy(fields()[10].schema(), other.HourlyVisibility);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.HourlyWindDirection)) {
        this.HourlyWindDirection = data().deepCopy(fields()[11].schema(), other.HourlyWindDirection);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.HourlyWindSpeed)) {
        this.HourlyWindSpeed = data().deepCopy(fields()[12].schema(), other.HourlyWindSpeed);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.HourlyPrecipitation)) {
        this.HourlyPrecipitation = data().deepCopy(fields()[13].schema(), other.HourlyPrecipitation);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.HourlyRelativeHumidity)) {
        this.HourlyRelativeHumidity = data().deepCopy(fields()[14].schema(), other.HourlyRelativeHumidity);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
    }

    /**
     * Creates a Builder by copying an existing WeatherEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(dk.sdu.bigdata.weather.producer.core.WeatherEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Station)) {
        this.Station = data().deepCopy(fields()[0].schema(), other.Station);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Date)) {
        this.Date = data().deepCopy(fields()[1].schema(), other.Date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Latitude)) {
        this.Latitude = data().deepCopy(fields()[2].schema(), other.Latitude);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Longitude)) {
        this.Longitude = data().deepCopy(fields()[3].schema(), other.Longitude);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Elevation)) {
        this.Elevation = data().deepCopy(fields()[4].schema(), other.Elevation);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Name)) {
        this.Name = data().deepCopy(fields()[5].schema(), other.Name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ReportType)) {
        this.ReportType = data().deepCopy(fields()[6].schema(), other.ReportType);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.Source)) {
        this.Source = data().deepCopy(fields()[7].schema(), other.Source);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.HourlyDryBulbTemperature)) {
        this.HourlyDryBulbTemperature = data().deepCopy(fields()[8].schema(), other.HourlyDryBulbTemperature);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.HourlySeaLevelPressure)) {
        this.HourlySeaLevelPressure = data().deepCopy(fields()[9].schema(), other.HourlySeaLevelPressure);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.HourlyVisibility)) {
        this.HourlyVisibility = data().deepCopy(fields()[10].schema(), other.HourlyVisibility);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.HourlyWindDirection)) {
        this.HourlyWindDirection = data().deepCopy(fields()[11].schema(), other.HourlyWindDirection);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.HourlyWindSpeed)) {
        this.HourlyWindSpeed = data().deepCopy(fields()[12].schema(), other.HourlyWindSpeed);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.HourlyPrecipitation)) {
        this.HourlyPrecipitation = data().deepCopy(fields()[13].schema(), other.HourlyPrecipitation);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.HourlyRelativeHumidity)) {
        this.HourlyRelativeHumidity = data().deepCopy(fields()[14].schema(), other.HourlyRelativeHumidity);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'Station' field.
      * @return The value.
      */
    public long getStation() {
      return Station;
    }


    /**
      * Sets the value of the 'Station' field.
      * @param value The value of 'Station'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setStation(long value) {
      validate(fields()[0], value);
      this.Station = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Station' field has been set.
      * @return True if the 'Station' field has been set, false otherwise.
      */
    public boolean hasStation() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Station' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearStation() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Date' field.
      * @return The value.
      */
    public java.lang.CharSequence getDate() {
      return Date;
    }


    /**
      * Sets the value of the 'Date' field.
      * @param value The value of 'Date'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Date' field has been set.
      * @return True if the 'Date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Date' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearDate() {
      Date = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Latitude' field.
      * @return The value.
      */
    public double getLatitude() {
      return Latitude;
    }


    /**
      * Sets the value of the 'Latitude' field.
      * @param value The value of 'Latitude'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setLatitude(double value) {
      validate(fields()[2], value);
      this.Latitude = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Latitude' field has been set.
      * @return True if the 'Latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Latitude' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearLatitude() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Longitude' field.
      * @return The value.
      */
    public double getLongitude() {
      return Longitude;
    }


    /**
      * Sets the value of the 'Longitude' field.
      * @param value The value of 'Longitude'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setLongitude(double value) {
      validate(fields()[3], value);
      this.Longitude = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Longitude' field has been set.
      * @return True if the 'Longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Longitude' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearLongitude() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'Elevation' field.
      * @return The value.
      */
    public double getElevation() {
      return Elevation;
    }


    /**
      * Sets the value of the 'Elevation' field.
      * @param value The value of 'Elevation'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setElevation(double value) {
      validate(fields()[4], value);
      this.Elevation = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'Elevation' field has been set.
      * @return True if the 'Elevation' field has been set, false otherwise.
      */
    public boolean hasElevation() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'Elevation' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearElevation() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }


    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.Name = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearName() {
      Name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'ReportType' field.
      * @return The value.
      */
    public java.lang.CharSequence getReportType() {
      return ReportType;
    }


    /**
      * Sets the value of the 'ReportType' field.
      * @param value The value of 'ReportType'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setReportType(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.ReportType = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'ReportType' field has been set.
      * @return True if the 'ReportType' field has been set, false otherwise.
      */
    public boolean hasReportType() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'ReportType' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearReportType() {
      ReportType = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'Source' field.
      * @return The value.
      */
    public java.lang.Object getSource() {
      return Source;
    }


    /**
      * Sets the value of the 'Source' field.
      * @param value The value of 'Source'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setSource(java.lang.Object value) {
      validate(fields()[7], value);
      this.Source = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'Source' field has been set.
      * @return True if the 'Source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'Source' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearSource() {
      Source = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'HourlyDryBulbTemperature' field.
      * @return The value.
      */
    public java.lang.Double getHourlyDryBulbTemperature() {
      return HourlyDryBulbTemperature;
    }


    /**
      * Sets the value of the 'HourlyDryBulbTemperature' field.
      * @param value The value of 'HourlyDryBulbTemperature'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setHourlyDryBulbTemperature(java.lang.Double value) {
      validate(fields()[8], value);
      this.HourlyDryBulbTemperature = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'HourlyDryBulbTemperature' field has been set.
      * @return True if the 'HourlyDryBulbTemperature' field has been set, false otherwise.
      */
    public boolean hasHourlyDryBulbTemperature() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'HourlyDryBulbTemperature' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearHourlyDryBulbTemperature() {
      HourlyDryBulbTemperature = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'HourlySeaLevelPressure' field.
      * @return The value.
      */
    public java.lang.Double getHourlySeaLevelPressure() {
      return HourlySeaLevelPressure;
    }


    /**
      * Sets the value of the 'HourlySeaLevelPressure' field.
      * @param value The value of 'HourlySeaLevelPressure'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setHourlySeaLevelPressure(java.lang.Double value) {
      validate(fields()[9], value);
      this.HourlySeaLevelPressure = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'HourlySeaLevelPressure' field has been set.
      * @return True if the 'HourlySeaLevelPressure' field has been set, false otherwise.
      */
    public boolean hasHourlySeaLevelPressure() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'HourlySeaLevelPressure' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearHourlySeaLevelPressure() {
      HourlySeaLevelPressure = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'HourlyVisibility' field.
      * @return The value.
      */
    public java.lang.Double getHourlyVisibility() {
      return HourlyVisibility;
    }


    /**
      * Sets the value of the 'HourlyVisibility' field.
      * @param value The value of 'HourlyVisibility'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setHourlyVisibility(java.lang.Double value) {
      validate(fields()[10], value);
      this.HourlyVisibility = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'HourlyVisibility' field has been set.
      * @return True if the 'HourlyVisibility' field has been set, false otherwise.
      */
    public boolean hasHourlyVisibility() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'HourlyVisibility' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearHourlyVisibility() {
      HourlyVisibility = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'HourlyWindDirection' field.
      * @return The value.
      */
    public java.lang.Double getHourlyWindDirection() {
      return HourlyWindDirection;
    }


    /**
      * Sets the value of the 'HourlyWindDirection' field.
      * @param value The value of 'HourlyWindDirection'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setHourlyWindDirection(java.lang.Double value) {
      validate(fields()[11], value);
      this.HourlyWindDirection = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'HourlyWindDirection' field has been set.
      * @return True if the 'HourlyWindDirection' field has been set, false otherwise.
      */
    public boolean hasHourlyWindDirection() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'HourlyWindDirection' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearHourlyWindDirection() {
      HourlyWindDirection = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'HourlyWindSpeed' field.
      * @return The value.
      */
    public java.lang.Double getHourlyWindSpeed() {
      return HourlyWindSpeed;
    }


    /**
      * Sets the value of the 'HourlyWindSpeed' field.
      * @param value The value of 'HourlyWindSpeed'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setHourlyWindSpeed(java.lang.Double value) {
      validate(fields()[12], value);
      this.HourlyWindSpeed = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'HourlyWindSpeed' field has been set.
      * @return True if the 'HourlyWindSpeed' field has been set, false otherwise.
      */
    public boolean hasHourlyWindSpeed() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'HourlyWindSpeed' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearHourlyWindSpeed() {
      HourlyWindSpeed = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'HourlyPrecipitation' field.
      * @return The value.
      */
    public java.lang.Object getHourlyPrecipitation() {
      return HourlyPrecipitation;
    }


    /**
      * Sets the value of the 'HourlyPrecipitation' field.
      * @param value The value of 'HourlyPrecipitation'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setHourlyPrecipitation(java.lang.Object value) {
      validate(fields()[13], value);
      this.HourlyPrecipitation = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'HourlyPrecipitation' field has been set.
      * @return True if the 'HourlyPrecipitation' field has been set, false otherwise.
      */
    public boolean hasHourlyPrecipitation() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'HourlyPrecipitation' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearHourlyPrecipitation() {
      HourlyPrecipitation = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'HourlyRelativeHumidity' field.
      * @return The value.
      */
    public java.lang.Double getHourlyRelativeHumidity() {
      return HourlyRelativeHumidity;
    }


    /**
      * Sets the value of the 'HourlyRelativeHumidity' field.
      * @param value The value of 'HourlyRelativeHumidity'.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder setHourlyRelativeHumidity(java.lang.Double value) {
      validate(fields()[14], value);
      this.HourlyRelativeHumidity = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'HourlyRelativeHumidity' field has been set.
      * @return True if the 'HourlyRelativeHumidity' field has been set, false otherwise.
      */
    public boolean hasHourlyRelativeHumidity() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'HourlyRelativeHumidity' field.
      * @return This builder.
      */
    public dk.sdu.bigdata.weather.producer.core.WeatherEvent.Builder clearHourlyRelativeHumidity() {
      HourlyRelativeHumidity = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WeatherEvent build() {
      try {
        WeatherEvent record = new WeatherEvent();
        record.Station = fieldSetFlags()[0] ? this.Station : (java.lang.Long) defaultValue(fields()[0]);
        record.Date = fieldSetFlags()[1] ? this.Date : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Latitude = fieldSetFlags()[2] ? this.Latitude : (java.lang.Double) defaultValue(fields()[2]);
        record.Longitude = fieldSetFlags()[3] ? this.Longitude : (java.lang.Double) defaultValue(fields()[3]);
        record.Elevation = fieldSetFlags()[4] ? this.Elevation : (java.lang.Double) defaultValue(fields()[4]);
        record.Name = fieldSetFlags()[5] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.ReportType = fieldSetFlags()[6] ? this.ReportType : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.Source = fieldSetFlags()[7] ? this.Source :  defaultValue(fields()[7]);
        record.HourlyDryBulbTemperature = fieldSetFlags()[8] ? this.HourlyDryBulbTemperature : (java.lang.Double) defaultValue(fields()[8]);
        record.HourlySeaLevelPressure = fieldSetFlags()[9] ? this.HourlySeaLevelPressure : (java.lang.Double) defaultValue(fields()[9]);
        record.HourlyVisibility = fieldSetFlags()[10] ? this.HourlyVisibility : (java.lang.Double) defaultValue(fields()[10]);
        record.HourlyWindDirection = fieldSetFlags()[11] ? this.HourlyWindDirection : (java.lang.Double) defaultValue(fields()[11]);
        record.HourlyWindSpeed = fieldSetFlags()[12] ? this.HourlyWindSpeed : (java.lang.Double) defaultValue(fields()[12]);
        record.HourlyPrecipitation = fieldSetFlags()[13] ? this.HourlyPrecipitation :  defaultValue(fields()[13]);
        record.HourlyRelativeHumidity = fieldSetFlags()[14] ? this.HourlyRelativeHumidity : (java.lang.Double) defaultValue(fields()[14]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WeatherEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<WeatherEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WeatherEvent>
    READER$ = (org.apache.avro.io.DatumReader<WeatherEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










